### ISSUE TITLE
Menu navigation

### ISSUE THREAD

**Issue by mikemccamon** [scorchingoyster/owasp-layout#24]
We should test abnormally long menu titles since the plan is some will be project names. My preference is the drop down width is dynamic long, with a set common minimum ( what we have now is fine) . There should be some examples in the menu hierarchy I sent a while back. I would prefer text doesn't wrap on menu itms

**Comment by scorchingoyster** [comment]
it doesn't wrap because it's an absolute element (expand its width as much as possible depending on the maximum width of the content), see below:
![image](https://user-images.githubusercontent.com/3586992/61176749-603f1300-a594-11e9-9632-92cc0a8b7e7c.png)

currently it takes its width from the widest item in the list, though with regard to the common minimum I have set it as 210px, which looks like:
![image](https://user-images.githubusercontent.com/3586992/61176773-d6437a00-a594-11e9-99fd-097e4b0e40bd.png)
